import { BookingDemo } from "@/components/demo";
import { EarlyAccessForm } from "@/components/early-access";
import { LineContact } from "@/components/line-contact";
import { Arrow, Calendar, Chat, Check, LinkIcon, Sparkle } from "@/components/icons";
import Link from "next/link";

const types = ["🎵 ดนตรี", "⚽ กีฬา", "🎨 ศิลปะ", "🗣️ ภาษา", "📚 กวดวิชา"];
export default function Home() {
  return <main className="overflow-hidden">
    <LineContact />
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 lg:px-8"><a href="#top" className="flex items-center gap-2 font-black text-[#183f33]"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#287b5c] text-white"><Calendar className="h-5 w-5" /></span>ClassMakeup</a><a href="#early-access" className="rounded-full bg-[#183f33] px-4 py-2.5 text-xs font-bold text-white sm:px-5 sm:text-sm">เข้าร่วม Early Access</a></nav>

    <section id="top" className="relative mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-20">
      <div className="absolute -left-40 top-20 -z-10 h-72 w-72 rounded-full bg-[#def4e9] blur-3xl" />
      <div><div className="inline-flex items-center gap-2 rounded-full bg-[#fff0c9] px-3 py-1.5 text-xs font-extrabold text-[#795817]"><Sparkle className="h-4 w-4" /> งานชดเชยที่เคยวุ่น ให้จบในลิงก์เดียว</div><h1 className="mt-6 text-[42px] font-black leading-[1.12] tracking-[-.035em] text-[#173c31] sm:text-6xl lg:text-[66px]">ไม่ต้องนัดคุย<br />ทุกรอบชดเชย</h1><p className="mt-6 max-w-xl text-base leading-8 text-[#596b64] sm:text-lg">ส่งลิงก์เดียวให้ผู้ปกครองดูสิทธิ์ เช็กรอบว่าง และจองคลาสเรียนชดเชยเอง สถาบันได้เวลาไปดูแลการสอนมากขึ้น</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#demo" className="flex items-center justify-center gap-2 rounded-2xl bg-[#ef7f5d] px-6 py-4 font-extrabold text-white transition hover:-translate-y-0.5 hover:bg-[#dd6d4c]">ลองจองคลาสดู <Arrow className="h-5 w-5" /></a><a href="#early-access" className="rounded-2xl border border-[#cbd8d1] bg-white px-6 py-4 text-center font-extrabold text-[#264e41]">เริ่มต้น 590 บาท/เดือน</a></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-bold text-[#607069]"><span className="flex items-center gap-1.5"><Check className="h-4 w-4 text-[#287b5c]" /> ไม่ต้องลงแอป</span><span className="flex items-center gap-1.5"><Check className="h-4 w-4 text-[#287b5c]" /> ใช้ได้ทุกมือถือ</span><span className="flex items-center gap-1.5"><Check className="h-4 w-4 text-[#287b5c]" /> เริ่มง่ายในไม่กี่นาที</span></div></div>
      <div className="relative dot-grid rounded-[40px] p-5 sm:p-9"><div className="float-card rounded-[30px] bg-white p-5 soft-shadow"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-[#76867f]">วันนี้ · 18 ก.ย.</p><p className="mt-1 font-black">ภาพรวมคลาสชดเชย</p></div><span className="rounded-full bg-[#dff5e9] px-3 py-1 text-xs font-bold text-[#176847]">ออนไลน์</span></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#fff5dc] p-4"><p className="text-3xl font-black text-[#8d651a]">8</p><p className="mt-1 text-xs text-[#715f3b]">รอเลือกเวลา</p></div><div className="rounded-2xl bg-[#e8f5ef] p-4"><p className="text-3xl font-black text-[#286a51]">12</p><p className="mt-1 text-xs text-[#4e6d61]">จองแล้วเดือนนี้</p></div></div><div className="mt-5 border-t border-[#edf1ee] pt-4"><p className="text-xs font-bold text-[#78877f]">รอบถัดไป</p><div className="mt-3 flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#f9d9cc] text-lg">🎹</span><div className="flex-1"><p className="text-sm font-bold">เปียโน · น้องมีนา</p><p className="text-xs text-[#78877f]">วันนี้ 17:00 · ครูมิน</p></div><span className="text-xs font-bold text-[#287b5c]">ยืนยันแล้ว</span></div></div></div></div>
    </section>

    <section className="border-y border-[#e4ebe6] bg-white py-10"><p className="text-center text-xs font-bold uppercase tracking-[.18em] text-[#819088]">ออกแบบมาเพื่อสถาบันของคุณ</p><div className="mx-auto mt-5 flex max-w-3xl flex-wrap justify-center gap-2 px-5">{types.map((t) => <span key={t} className="rounded-full bg-[#f4f7f4] px-4 py-2 text-sm font-bold text-[#50635b]">{t}</span>)}</div></section>

    <section className="mx-auto max-w-6xl px-5 py-20 lg:px-8 lg:py-28"><div className="max-w-2xl"><p className="text-sm font-extrabold text-[#ef7f5d]">ลดแชต ลดหลุด ลดลืม</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">จากหลายสิบข้อความ<br />เหลือเพียง 3 ขั้นตอน</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[[LinkIcon,"ส่งลิงก์ให้ผู้ปกครอง","แชร์ผ่าน LINE หรือช่องทางเดิม ไม่ต้องให้ใครติดตั้งแอปเพิ่ม"],[Calendar,"เลือกรอบที่ยังว่าง","ผู้ปกครองเห็นเฉพาะรอบที่จองได้ พร้อมจำนวนที่นั่งแบบชัดเจน"],[Check,"ยืนยันได้ทันที","ทั้งสองฝ่ายเห็นข้อมูลตรงกัน ลดการถามซ้ำและความผิดพลาด"]].map(([Icon,title,text],i) => { const I = Icon as typeof Check; return <div key={String(title)} className="relative rounded-[26px] border border-[#e0e8e3] bg-white p-6"><span className="absolute right-5 top-4 text-5xl font-black text-[#edf2ef]">0{i+1}</span><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e6f4ed] text-[#287b5c]"><I /></span><h3 className="mt-6 text-lg font-black">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-[#677770]">{String(text)}</p></div>})}</div></section>

    <section id="demo" className="bg-[#eef6f1] py-20 lg:py-28"><div className="mx-auto grid max-w-6xl gap-10 px-5 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:px-8"><div><p className="text-sm font-extrabold text-[#287b5c]">Interactive demo</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">ลองในมุม<br />ผู้ปกครอง</h2><p className="mt-5 max-w-md leading-7 text-[#607069]">เลือกหนึ่งรอบ กดยืนยัน แล้วลองยกเลิกได้เลย ข้อมูลตัวอย่างนี้ทำงานบนหน้าเว็บเท่านั้น</p><div className="mt-7 flex items-start gap-3 rounded-2xl bg-white/70 p-4 text-sm text-[#50645b]"><Chat className="mt-0.5 h-5 w-5 shrink-0 text-[#287b5c]" /><p><strong className="block text-[#263f36]">ไม่ต้องล็อกอินในเดโม</strong>ประสบการณ์จริงออกแบบให้สั้น ชัด และเป็นมิตรกับผู้ปกครอง</p></div></div><BookingDemo /></div></section>

    <section id="early-access" className="relative py-20 lg:py-28"><div className="absolute right-0 top-0 -z-10 h-96 w-96 rounded-full bg-[#fff0cf] blur-3xl" /><div className="mx-auto grid max-w-6xl gap-10 px-5 lg:grid-cols-[.75fr_1.25fr] lg:px-8"><div><p className="text-sm font-extrabold text-[#ef7f5d]">Early Access</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">ช่วยเราสร้าง<br />ให้ตรงกับงานจริง</h2><p className="mt-5 leading-7 text-[#607069]">เรากำลังรับสถาบันกลุ่มแรกเพื่อทดลอง ClassMakeup และร่วมให้ความเห็นก่อนเปิดตัว</p><div className="mt-8 rounded-[24px] bg-[#173f33] p-6 text-white"><p className="text-sm text-white/65">ราคา Early Access</p><p className="mt-2 text-4xl font-black">590 <span className="text-base font-bold text-white/70">บาท/เดือน</span></p><p className="mt-3 text-xs leading-5 text-white/60">แสดงความสนใจก่อนได้ ยังไม่มีการเรียกเก็บเงิน</p></div></div><EarlyAccessForm /></div></section>

    <footer className="border-t border-[#dfe7e2] px-5 py-8"><div className="mx-auto flex max-w-6xl flex-col gap-3 text-center text-xs text-[#74827c] sm:flex-row sm:items-center sm:justify-between sm:text-left"><p className="font-black text-[#294c40]">ClassMakeup</p><div className="flex justify-center gap-4"><Link href="/privacy" className="underline">นโยบายความเป็นส่วนตัว</Link><p>สร้างเพื่อให้ทุกคลาสชดเชยเป็นเรื่องง่าย · MVP 2026</p></div></div></footer>
  </main>;
}
